#Playbook is nothing but list of plays
- name: PLAY-1
  hosts: localhost
  tasks:
  - name: PLAY-1 & TASK-1
    ansible.buildin.debug:
      msg: "Hello from PLAY-1 ans TASk-1"

- name: PLAY-2
  hosts: localhost
  tasks:
  - name: PLAY-2 & TASK-2
    ansible.buildin.debug:
      msg: "Hello from PLAY-2 ans TASk-2"    